### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by casperdcl** [CCPPETMR/SIRF#1]
- [ ] dependency install instructions
    + [ ] Git
    + [ ] CMake
    + [ ] Boost
    + [ ] SWIG
    + [ ] CUDA
    + [ ] MatLab
    + [ ] Python
    + [ ] PTVS
- [ ] main install instructions
    + git clone --recursive && make
- [ ] GLUE
    + [ ] CMakeLists.txt, inspired by:
        * [ ] generic instructions from `Makefile`s
            - [x] iUtilities
                + [x] iutilities
                + [x] c2m
            - [ ] xSTIR
                + [x] cSTIR
                + [ ] pSTIR
                + [ ] mSTIR
            - [ ] xGadgetron
                + [ ] cGadgetron
                + [ ] pGadgetron
                + [ ] mGadgetron
        * [ ] windows-specific instructions from `vcxproj[.filters]`
            - [ ] iUtilities
            - [ ] xSTIR
            - [ ] xGadgetron
    + [ ] make.bat (windows make)
    + [x] Makefile (gnumake)
        - mkdir build && cd build && cmake .. && make

**Comment by casperdcl** [comment]
superceded by events
