### ISSUE TITLE
SIRF Release 1.0.0-rc.1 checklist

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF#114]
## Release Checklist

`VER=1.0.0-rc.1`

1. SIRF
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] update version numbers in [SIRF/CMakeLists.txt](CMakeLists.txt)
 - [x] update version numbers in the [doc/UsersGuide.md](doc/UserGuide.md) etc
 - [x] `git push`
 - [x] close #120 
 - [x] check Travis
 - [x] run doxygen, check and send files for uploading
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`
 
2. SuperBuild
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] update `SIRF-Superbuild/version_config.cmake` with new `SIRF_TAG`
 - [x] `git push`
 - [x] check Travis
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

3. Virtual Machine

 - [x] update version number in [VM_version.txt](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/VM_version.txt)
 - [x] update `vb.name` in [vagrant/vagrantfile](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/vagrant/Vagrantfile)
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] `git push`
 - [x] `vagrant up`
 - [x] remove screen lock
 - [x] add English UK keyboard
 - [x] run the zerofill trick
 - [x] Virtualbox Guest Additions
 - [x] export the VM and upload to website
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

4. Website
 - [x] update Software page (version info, VM etc)
 - [x] upload doxygen
 - [x] update link in [Wiki](https://github.com/CCPPETMR/SIRF/wiki/Documentation)
 - [x] add news flash

5. Announce
 - [x] Send email

 #### zerofill trick
 
 ```
sudo dd if=/dev/zero of=/EMPTY bs=1M
sudo rm -f /EMPTY
```

**Comment by KrisThielemans** [comment]
thanks @paskino.
I've changed the version number to 1.0.0-rc1. no need to change this for the VM I think.

I cannot see how you can create the final VM before all the stuff above is ticked though... Seems to me you need to untick from `vagrant up`. or you could choose the update it I guess.

**Comment by KrisThielemans** [comment]
@casperdcl do we need a docker tag step? (If so, please put it in the original checklist.md as well)

**Comment by paskino** [comment]
@KrisThielemans you are absolutely right. Today I  created a new VM to test if that worked.

**Comment by casperdcl** [comment]
@KrisThielemans 

1. I'd really recommend `1.0.0-rc.1` since `rc.1 < rc.10` but `rc1 > rc10` by semver's convention
2. I added my docker branch to milestone 1.0.0 for the SuperBuild so that the docker side of things will be completely automated by Travis. Will merge nowish.

**Comment by KrisThielemans** [comment]
sure. `rc.1` is fine for me.

**Comment by KrisThielemans** [comment]
@casperdcl should we tag SIRF_data as well? I guess so

**Comment by KrisThielemans** [comment]
@paskino, please update [doc/ReleaseChecklist.md](doc/ReleaseChecklist.md) according to any changes here after we're done.

**Comment by paskino** [comment]
Only SIRF TAG is different this time?

**Comment by paskino** [comment]
What do you reckon? The VM version can be 1.0.0? without rc.1? Or with?

**Comment by KrisThielemans** [comment]
let's leave with. then no changes presumably.
people can always update afterwards

**Comment by paskino** [comment]
There's a travis error https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/jobs/341865694 which is related to a network problem rather than our software.

**Comment by casperdcl** [comment]
It's merged in now (#90) and @KrisThielemans deleted the branch which is why the PR build failed. `master` seems to be building fine though apart from https://travis-ci.org/CCPPETMR/SIRF-SuperBuild/jobs/341868335 which I just restarted

**Comment by casperdcl** [comment]
ok all passed, please do continue with the checklist...
