### ISSUE TITLE
Release 1.0.0 checklist

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/SIRF#156]
```
VER=1.0.0
```

1. SIRF
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] update version numbers in [SIRF/CMakeLists.txt](CMakeLists.txt)
 - [x] update version numbers in the [doc/UsersGuide.md](doc/UserGuide.md) etc
 - [x] run all demos
 - [x] run ctest
 - [x] `git push` 
 - [x] check Travis
 - [x] run doxygen, check and send files for uploading
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`
 
2. SuperBuild
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] update `SIRF-Superbuild/version_config.cmake` with new `SIRF_TAG`
 - [x] `git push`
 - [x] check Travis
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

3. Virtual Machine

 - [x] update version number in [VM_version.txt](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/VM_version.txt)
 - [x] update `vb.name` in [vagrant/vagrantfile](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/vagrant/Vagrantfile)
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] `git push`
 - [x] `vagrant up`
 - [x] Virtualbox Guest Additions
 - [x] run `first_run.sh` script (gnome settings and zero-fill trick)
 - [x] [deselect](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/vagrant/README.md#notes-about-ubuntu-box-for-version-100) the serial port.
 - [x] export the VM
 - [x] ctest on VM
 - [x] upload to website
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

4. Website
 - [x] update Software page (version info, VM etc)
 - [x] upload doxygen
 - [x] update link for doxygen in [Wiki](https://github.com/CCPPETMR/SIRF/wiki/Software-Documentation)
 - [x] add news flash

5. Announce
 - [x] Send email

6. Tag wikis
 - [x] `git clone https://github.com/CCPPETMR/SIRF.wiki.git; cd SIRF.wiki` (or pull)
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`
 - [x] `git clone https://github.com/CCPPETMR/CCPPETMR_VM.wiki.git; cd CCPPETMR_VM.wiki` (or pull)
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

https://github.com/CCPPETMR/SIRF/issues/new

**Comment by KrisThielemans** [comment]
SIRF travis has a few failures, see #158 and https://github.com/CCPPETMR/SIRF-SuperBuild/issues/97. These arent really SIRF related as far as I can see.

**Comment by paskino** [comment]
Running `ctest -c --verbose` I get 
```
Test command: /usr/local/bin/ctest "-C" ""
1: Test timeout computed to be: 9.99988e+06
1: Test project /home/sirfuser/devel/buildVM/builds/SIRF/build
1:     Start 1: PET_TEST_CPLUSPLUS
1: 1/3 Test #1: PET_TEST_CPLUSPLUS ...............   Passed    0.00 sec
1:     Start 2: PET_TESTS_PYTHON
1: 2/3 Test #2: PET_TESTS_PYTHON .................   Passed   13.72 sec
1:     Start 3: MR_TESTS_PYTHON
1: 3/3 Test #3: MR_TESTS_PYTHON ..................   Passed    5.53 sec
1: 
1: 100% tests passed, 0 tests failed out of 3
```

Seems the C++ tests do not run.

**Comment by KrisThielemans** [comment]
I guess you mean any MR C++ tests? There aren't any yet...

**Comment by paskino** [comment]
Based on the output of `ctest -c --verbose`, the `PET_TEST_CPLUSPLUS` take 0.00 sec. I seem to remember that they took about 20 sec. However, they are positive. 

So either my computer is **very** fast or they don't run.

**Comment by rijobro** [comment]
It's surprising that it takes 0.00. What output do you see from the verbose? Something about not being able to find the files, perhaps? You should see some output that looks like:
`Starting iteration 1	KL 49.1491`

**Comment by paskino** [comment]
That is exactly the output of `ctest --verbose`
It seems that it's not running the tests. However I'm redoing the VM as it turns out I had actually built v1.0.0-rc.3

**Comment by rijobro** [comment]
You should see quite a lot of text for each test. If what you copied and pasted is the whole output, then I would guess that the verbose argument is not being passed. 

You've got empty quotation marks in the line you posted earlier:`Test command: /usr/local/bin/ctest "-C" ""`, which makes me think the same thing.

I would say - try and sort out the verbose output first, then (hopefully) the C++ problem should become apparent.

**Comment by rijobro** [comment]
Can you try cd'ing to the build directory (it looks like `/home/sirfuser/devel/buildVM/builds/SIRF/build` and running `ctest --verbose` from there?

**Comment by KrisThielemans** [comment]
There were a sequence of things here.
- test4 failed in 1.0.0-rc.3 due to file location. @evgueni-ovtchinnikov had fixed that for 1.0.0.
- @paskino was running from SuperBuild 1.0.0-rc.3
- `update_VM.sh` didn't update an existing VM to 1.0.0 due to https://github.com/CCPPETMR/CCPPETMR_VM/issues/74 (fixed now)

All is well if I update my VM now. (It is maybe somewhat confusing that CCPPETMR_VM was tagged with 1.0.0 already and the fix is applied after that, but I don't think this matters too much. This kind of stuff will be resolved once we merge the VM and the SB).

However, the test above reported `Passed` while it actually didn't pass! I've created #156 for this.

Thanks @paskino for being so eagle-eyed.
