### ISSUE TITLE
SIRF 1.1.1 checklist

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [CCPPETMR/SIRF#178]
```
VER=1.1.1
```

1. SIRF
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] update version numbers in [SIRF/CMakeLists.txt](CMakeLists.txt)
 - [x] update version numbers in the [doc/UsersGuide.md](doc/UserGuide.md) etc
 - [x] run all demos
 - [x] run ctest
 - [x] `git push` 
 - [x] check Travis
 - [x] run doxygen, check, send files for uploading and update the doxygen link on Wiki
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`
 
2. SuperBuild
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] update `SIRF-Superbuild/version_config.cmake` with new `SIRF_TAG`
 - [x] `git push`
 - [x] check Travis
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

3. Virtual Machine

 - [x] update version number in [VM_version.txt](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/VM_version.txt)
 - [x] update `vb.name` in [vagrant/vagrantfile](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/vagrant/Vagrantfile)
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] `git push`
 - [x] `vagrant up`
 - [x] Virtualbox Guest Additions
 - [x] run `first_run.sh` script (gnome settings and zero-fill trick)
 - [x] [deselect](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/vagrant/README.md#notes-about-ubuntu-box-for-version-100) the serial port.
 - [x] export the VM
 - [x] ctest on VM
 - [x] upload to website
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

4. Website
 - [x] update Software page (version info, VM etc)
 - [x] upload doxygen
 - [x] update link for doxygen in [Wiki](https://github.com/CCPPETMR/SIRF/wiki/Software-Documentation)
 - [x] add news flash

5. Announce
 - [x] Send email

6. Tag wikis
 - [x] `git clone https://github.com/CCPPETMR/SIRF.wiki.git; cd SIRF.wiki` (or pull)
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`
 - [x] `git clone https://github.com/CCPPETMR/CCPPETMR_VM.wiki.git; cd CCPPETMR_VM.wiki` (or pull)
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

**Comment by KrisThielemans** [comment]
`update SIRF-Superbuild/version_config.cmake with new SIRF_TAG`  checked? we don't have a new SIRF_TAG yet...

**Comment by evgueni-ovtchinnikov** [comment]
i understand you are asking whether to check that box?

i check a box if nothing needs to be done (e.g. i checked unchanged notice.txt last time) otherwise it would look as if something needs yet to be done

**Comment by evgueni-ovtchinnikov** [comment]
i have put in SIRF/changes.md what i remember, please add what you remember

**Comment by KrisThielemans** [comment]
thanks. yes, we tick boxes when nothing needs to be done, but that particular one needs editing of version_config.cmake once SIRF is tagged :-; sorry about the confusion

**Comment by paskino** [comment]
I ticked it. I presume the new tag will be `v1.0.0` and I already changed it in https://github.com/CCPPETMR/SIRF-SuperBuild/pull/120

**Comment by KrisThielemans** [comment]
ok, somewhat dangerous to push then if the tag doesn't exist yet.

by the way, before you tag, don't forget to pull first. should put that in the checklist really as `git pull;git tag...`. (not this one, the one on master)

**Comment by paskino** [comment]
Dangerous, but in a separate branch. And for few minutes.

**Comment by KrisThielemans** [comment]
sorry. don't understand your comment.

**Comment by paskino** [comment]
I meant that not being on master and expecting sirf to be tagged soon it's not a big deal.
