### ISSUE TITLE
SIRFReg code review

### ISSUE THREAD

**Issue by rijobro** [CCPPETMR/SIRF#213]
- [x] Set parameters with strings ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222565500))
- [ ] Pythonic testing ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222562789))
- [x] `if (norm > epsilon)` output should be `#ifndef NDEBUG`
- [x] throw error for casting to unknown type ([here](https://github.com/CCPPETMR/SIRF/pull/211/files/b724ae898f1fc75135688cc5d254a0e46715d88f#r222884669)). Also use `else if`.
- [x] break if can't do crop ([here](https://github.com/CCPPETMR/SIRF/pull/211/files/b724ae898f1fc75135688cc5d254a0e46715d88f#r222884729)).
- [x] move image origin when cropping ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222885694))
- [x] image match short circuit booleans ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222887792))
- [x] `dump_` -> `print` ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222888198))
- [x] `update` -> `process` ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222899935))
- [x] SIRFReg set parameter file with `const std::string&` ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222899990))
- [x] Rename "back" transformation "inverse" ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222900226))
- [x] SIRFReg`check_parameters` should be const ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222900300))
- [x] SIRFReg: Only store deformation fields. Generate displacement fields as necessary ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222900510))
- [x] Clarify terminology between displacement and deformation ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222900593))
- [x] Weighted mean: throw error if metadata don't match ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222900971))
- [x] Use `isempty()` instead of `size() == 0` ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222904293))
- [x] SIRFRegMat44: remove `fill` ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222904639))
- [x] SIRFRegMat44: virtual `save_to_file` method ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222904755))
- [x] SIRFRegMat44: `operator[]` should return `float [4]` ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222905145))
- [x] Don't use `using namespace std` ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r222923244))
- [x] Superclasses should exist for resampling and registration which know nothing about NiftyReg/nifti. This will allow for inclusion of different registration packages in the future.
- [x] Registration classes should return SIRFRegTransformation. You should be able to get this as an affine/deformation/displacement transformation. If a non-rigid registration algorithm was used, an error should be thrown upon trying to return an affine transformation matrix.
- [x] Interpolation types in the registration class should use enum
- [ ] Namespaces should be used in python/Matlab. Should be sirf.Reg.Nifty.RigidRegistration instead of pSIRFRegNiftyAladin. This will allow for generic changing of registration engines.
- [x] Instead of relying solely on parameter files, why not have a set_parameter(parameter_name, val) method (this saves exposing all methods of all registration packages, which is not sustainable).
- [x] Return `shared_ptr to avoid copying where possible.
- [x] Check SimpleITK python registration to look at similarities/differences, and decide if anything needs to change to make them any closer (might make it easier for incorporating other registration packages in the future).
- [x] Implement new hierarchy for images (#212).
   - [x] Whilst waiting for this, put `GeometricalInfo` into `NiftiImageData`
- [x] Rename CMake variables for grouping.
- [x] Make SIRFReg examples (essentially split the ctests into separate files)
- [x] Remove files that have accidentally been added to PR ([here](https://github.com/CCPPETMR/SIRF/pull/211#discussion_r223684939)).
- [x] Rename `NiftiImage` -> `NiftiImageData` ([here](https://github.com/CCPPETMR/SIRF/issues/212#issuecomment-428264997)).
- [x] Check documentation of each file is correct/up-to-date (authorship, copyright, doxygen).
- [x] All include files should be accessed with: `#include "sirf/reg/..."` (#202)
- [x] In python, should be `import sirf`, not `import pSIRF`. Do `import sirf` and help to see packages and make sure you follow naming convention (`reg` or `Reg`?)
- [x] test affinetransformation::get_inverse (C++, python, matlab)
- [ ] fill from array in python
- [x] masks for reference and floating images (matlab: f3d, python: aladin & f3d)
- [x] `sirfreg_build_python` -> `build_python`. same for matlab.
- [x] set masks for reference and floating images in matlab and python

**Comment by KrisThielemans** [comment]
@rijobro I guess you can tick some of these already?

**Comment by KrisThielemans** [comment]
@rijobro, I'm assuming this can be closed?

**Comment by rijobro** [comment]
yup
