### ISSUE TITLE
SIRF 2.0.0-rc.3 checklist

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF#381]
## Release Checklist
Set version variable of the release for further steps, e.g. using the format
```
VER=2.0.0-rc.3
```

1. SIRF
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] update version numbers in [SIRF/CMakeLists.txt](https://github.com/CCPPETMR/SIRF/blob/master/CMakeLists.txt)
 - [x] update version numbers in the [doc/UsersGuide.md](https://github.com/CCPPETMR/SIRF/blob/master/doc/UserGuide.md) etc
 - [x] run all demos
 - [x] run ctest
 - [x] `git push` 
 - [x] check Travis
 - [x] run doxygen, check, send files for uploading and update the doxygen link on Wiki
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`
 
2. SuperBuild
 - [ ] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] update `SIRF-Superbuild/version_config.cmake` with new `SIRF_TAG` (and `STIR_TAG` etc if necessary)
 - [x] `git push`
 - [x] check Travis
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

3. Virtual Machine

 - [x] update version number in [VM_version.txt](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/VM_version.txt)
 - [x] update `vb.name` in [vagrant/vagrantfile](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/vagrant/Vagrantfile)
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] `git push`
 - [x] `vagrant up`
 - [x] Virtualbox Guest Additions
 - [x] run `first_run.sh` script (gnome settings and zero-fill trick)
 - [x] [deselect](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/vagrant/README.md#notes-about-ubuntu-box-for-version-100) the serial port.
 - [x] export the VM
 - [x] ctest on VM
 - [x] upload to website
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

4. Website
 - [ ] update Software page (version info, VM etc)
 - [ ] upload doxygen
 - [ ] update link for doxygen in [Wiki](https://github.com/CCPPETMR/SIRF/wiki/Software-Documentation)
 - [ ] add news flash

5. Announce
 - [ ] Send email

6. Tag wikis
 - [ ] `git clone https://github.com/CCPPETMR/SIRF.wiki.git; cd SIRF.wiki` (or pull)
 - [ ] `git tag -a v$VER -m "version $VER"`
 - [ ] `git push origin v$VER`
 - [ ] `git clone https://github.com/CCPPETMR/CCPPETMR_VM.wiki.git; cd CCPPETMR_VM.wiki` (or pull)
 - [ ] `git tag -a v$VER -m "version $VER"`
 - [ ] `git push origin v$VER`

**Comment by KrisThielemans** [comment]
@paskino @evgueni-ovtchinnikov where are we with this? I think the check list is incomplete. I see for instance that the SB is tagged with 2.0.0.-rc.4.

I also see that version numbers in the files still have the -rc.*, although we had said we'd remove these already (such that we could just re-tag). That's not a major problem of course, it just means updating it all and releasing a new VM.

By the way, did anyone check the updated doxygen?

**Comment by paskino** [comment]
The status is that:

1. SuperBuild is off sync w.r.t. rc number because of an initial mistake. Its rc is +1
2. I believe we could aim at releasing 2.0.0 directly as you were happy with the 2.0.0-rc.3 VM and there have been no changes since then.

**Comment by KrisThielemans** [comment]
definitely go for 2.0.0 now. only changes are the version numbers, CHANGES.md, checklist changes, and final!
(ok, SIRF-exercises)

**Comment by KrisThielemans** [comment]
supperseded by #383
