### ISSUE TITLE
Release 2.0.0 checklist

### ISSUE THREAD

**Issue by paskino** [CCPPETMR/SIRF#383]
```
VER=2.0.0
```

1. SIRF
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] update version numbers in [SIRF/CMakeLists.txt](https://github.com/CCPPETMR/SIRF/blob/master/CMakeLists.txt)
 - [x] update version numbers in the [doc/UsersGuide.md](https://github.com/CCPPETMR/SIRF/blob/master/doc/UserGuide.md) etc
 - [x] run all demos
 - [x] run ctest
 - [x] `git push` 
 - [x] check Travis
 - [x] run doxygen, check, send files for uploading and update the doxygen link on Wiki
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`
 - [x] Add release title and description including everything since the last release
 
2. SuperBuild
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] update `SIRF-Superbuild/version_config.cmake` with new `SIRF_TAG` (and `STIR_TAG` etc if necessary)
 - [x] `git push`
 - [ ] check Travis
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

3. Virtual Machine

 - [x] update version number in [VM_version.txt](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/VM_version.txt)
 - [x] update `vb.name` in [vagrant/vagrantfile](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/vagrant/Vagrantfile)
 - [x] update `CHANGES.md`
 - [x] update `NOTICE.txt`
 - [x] `git push`
 - [x] `vagrant up`
 - [x] Virtualbox Guest Additions
 - [x] run `first_run.sh` script (gnome settings and zero-fill trick)
 - [x] check that the serial port is [deselected](https://github.com/CCPPETMR/CCPPETMR_VM/blob/master/vagrant/README.md#notes-about-ubuntu-box-for-version-100).
 - [x] export the VM
 - [x] ctest on VM
 - [x] upload to website
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`
 
4. SIRF-Exercises
 - [x] run all exercises
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`
 
5. Website
 - [x] update Software page (version info, VM etc)
 - [ ] upload doxygen
 - [ ] update link for doxygen in [Wiki](https://github.com/CCPPETMR/SIRF/wiki/Software-Documentation)
 - [x] add news flash

6. Announce
 - [x] Send email

7. Tag wikis
 - [x] `git clone https://github.com/CCPPETMR/SIRF.wiki.git; cd SIRF.wiki` (or pull)
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`
 - [x] `git clone https://github.com/CCPPETMR/CCPPETMR_VM.wiki.git; cd CCPPETMR_VM.wiki` (or pull)
 - [x] `git tag -a v$VER -m "version $VER"`
 - [x] `git push origin v$VER`

**Comment by KrisThielemans** [comment]
@paskino, you've done a lot of these now. can you "check" the boxes?

I note that http://www.ccppetmr.ac.uk/downloads still mentions the 2.0.0-rc.1 VM. should now use the generic VM DOI (one less thing to do in the future!). Can we in the zenodo page for the VM mention the VB version?

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov thanks for updating the downloads page. is this all done? Please close if so, or finalise if not :-)
